### ISSUE TITLE
Creating a Landing Page Structure

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/CareerPath#1]
## AIM

Create a Landing Page for the Main Website using HTML. 

## Sections

- Logo
- Title
- Short Description

**Comment by Sapna2001** [comment]
@HarshCasper can you please assign me this issue.

**Comment by HarshCasper** [comment]
Hello @Sapna2001. I have assigned you the Issue. You will work with @Zinkuth on this, who had taken up this Job Earlier.

Both of you can coordinate on Slack over this by creating a Landing Page with HTML and CSS.

**Comment by Zinkuth** [comment]
I & @Sapna2001 will make the Landing Page.
