### ISSUE TITLE
Create the Tech Path Page

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/CareerPath#17]
## AIM

Creating a Tech Path Page

## Features

- Visually Appealing Design with Graphics to show various Tech Paths that are to be followed
- Add a Section of Projects to be made.
- Create sections for: Web Dev, Machine Learning, Android Dev, Cybersecurity and DS-Algo. Place Lorem Ipsum Texts for now.

**Comment by vanshiikaa** [comment]
I can work on this

**Comment by HarshCasper** [comment]
I have assigned you the Issue @vanshiikaa 

You can make a Pull Request now.

**Comment by vanshiikaa** [comment]
Okayy
