### ISSUE TITLE
Creating a Chatbot for the Website

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/CareerPath#18]
## AIM

Create a Chatbot for the Website.

## Features

- Add Intents to help out the Student with knowing about the Website.
- Sharing Resources for various Development Tracks.
- Giving Information where to apply for Internships and all.

For people who are now starting with Chatbot Development are advised to get started with this [course](https://cognitiveclass.ai/courses/how-to-build-a-chatbot).

**Comment by ishi0301** [comment]
Please assign me this issue

**Comment by Samiksha99** [comment]
is the issue available or assigned?
