### ISSUE TITLE
Header_and_Footer is not proper

### ISSUE THREAD

**Issue by Shantanujain18** [HarshCasper/CareerPath#23]
Unable to find style.css

**Comment by HarshCasper** [comment]
Hello @Shantanujain18 

Thanks for raising this issue. As far as I understand, I can see a `style.css` file with Headers and Footers [here](https://github.com/HarshCasper/CareerPath/blob/master/Header_and_Footer/style.css)

**Comment by sarthakkundra** [comment]
Hi @HarshCasper I would like to work on this. Also I have not yet built the project so do you want some alignment issues solved or you need UI improvements?

**Comment by Mu-C00L** [comment]
I would like to work on this issue.
