### ISSUE TITLE
Creating a 404 Page

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/CareerPath#4]
## AIM

Create a 404 Page.

## Features

- Directed whenever a User clicks an Invalid Link
- Use some animation if possible

**Comment by ishi0301** [comment]
I would like to work on this

**Comment by HarshCasper** [comment]
@ishi0301 You can currently focus on the Logo Designing Part. Harsha is already making the 404 Page.

**Comment by Harshak50** [comment]
@HarshCasper  please assign this to me
