### ISSUE TITLE
Create an "About Us" Page

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/CareerPath#5]
## AIM

Create an "About Us" Page for the Website.

## Features:

- Use basic HTML for Structuring the Page.
- Mention the main objectives of the Website.
- Create a "Contributor" Section

**Comment by jyotibalodhi** [comment]
I would like to work on the issue!

**Comment by HarshCasper** [comment]
You have been assigned this Issue @jyotibalodhi 

You can bring up your own design in this and update us on the Slack Channel about this.

**Comment by procheta1999** [comment]
I would like to work on this issue.
