### ISSUE TITLE
Make a Logo for the Website

### ISSUE THREAD

**Issue by HarshCasper** [HarshCasper/CareerPath#6]
## AIM

Create a Functional Logo for the Main Website

## Features

Make use of tools like Adobe Photoshop or GIMP to make a Logo for the Website.

**Comment by ishi0301** [comment]
I just found a site named as wix logo maker. We can try to make the logo of our webpage from this site. If it's possible then please assign me this.

**Comment by HarshCasper** [comment]
Hello @ishi0301 

We can use Logo Making Services like Wix, but we need more control over the designing. Designing it with a Software like Adobe XD, Photoshop or GIMP would be preferred a lot. 

You can take a look at these tutorials and come up with a new design:

- [Logo Design Photoshop Tutorial](https://www.youtube.com/watch?v=mJof0-TtO6c)
- [How to make a Logo in Photoshop](https://www.youtube.com/watch?v=NVKju7nZvDI)
- [Photoshop CS6 Logo Design Tutorial](https://www.youtube.com/watch?v=7-jH-6gqJK0)

If you would like to take up this Issue by design a custom logo in Photoshop, I will assign it to you. It will be a learning experience for you as well with designing.
